name: data-science-handbook
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn=0.23.2
  - jupyterlab=2.2.6
  - pip=21.0.1
  - python=3.9.1
  - matplotlib=3.3.4
  - numpy=1.20.0
  - pandas=1.2.1
  - pillow=8.1.0
  - scipy=1.6.0
  - seaborn=0.11.1
    
